apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: calendar-service
  description: The Calendar Service
  tags:
    - history
spec:
  type: openapi
  lifecycle: production
  owner: intocare
  definition:
    $text: ./openapi.yaml